### ISSUE TITLE
OhmCoin (OHMC) White Paper

### ISSUE THREAD

**Issue by AlexSGabor** [theohmproject/ohmcoin-whitepaper#4]
Is **OhmCoin** a token? 

If so, you might be dead in the water as the SEC will have to have a registration statement for any larger amounts of real money coming in for this project.  

Who is working on the White Paper? https://github.com/theohmproject/ohmcoin-whitepaper/pull/1

https://www.cnbc.com/2018/06/06/sec-chairman-clayton-says-agency-wont-change-definition-of-a-security.html

https://cryptoslate.com/coinbase-to-receive-sec-registration-and-expand-digital-asset-listings/

http://fortune.com/2018/06/04/blockchain-airdrops/

https://www.finder.com.au/meet-the-secs-first-crypto-czar

**Comment by 2a5A1Ghu1** [comment]
It's not a token, as we move forward and start the process of getting 501c3 status for the ohm project you will see that ohmcoin itself is a coin used to facilitate donations and not to fund projects with probability of returns such as found in an ICO or IPO. 

Basically, filling a malnourished childs stomach in Africa via a donation through the ohmcoin network would be the opposite of an ICO. It generates a loss for the donator without a guaranteed return of investment but they would get a tax write off.

So no not a token...

https://github.com/theohmproject/ohmcoin-whitepaper/pull/1 The intro was written by one of our devs who has since left for heath reasons. Therefore I am currently writing the first draft of the white paper. Being that is a first draft it is in the develop tree. Anyone is allowed and encouraged to make suggested changes to it as we develop it out. 

I am closing this issue reopen it if you have any other questions.

**Comment by AlexSGabor** [comment]
How do I edit your white paper, make changes, or even buy into the coin? I'm very new to Github.com.

I wrote a white paper for EyeCoin and it was initially accepted by the Board of Directors but then later rejected after it was edited by me a second time through. The Infinite Freedom Foundation was supposed to get paid $5,000 for it but no luck collecting on that promise.
Here are some links related to this discussion that might encourage you to keep this discussion open:
https://www.linkedin.com/pulse/snapchange-alex-s-gabor
https://www.linkedin.com/pulse/gabors-law-bitcoin-alex-s-gabor/

**Comment by AlexSGabor** [comment]
Here is what I wrote for Eyecoin:
I own the copyright.
https://docs.google.com/document/d/1y8-EmS7u-5zBF0_90zqUNV8l5-_2i88fieHGFkfuX5o/edit?usp=sharing

**Comment by 2a5A1Ghu1** [comment]
![screen shot 2018-06-15 at 7 24 33 am](https://user-images.githubusercontent.com/13294167/41473096-2e15a0d6-706d-11e8-83d0-2fb5de0676c2.png)
